In [1]:
import polars as pl
import pandas as pd

# General Metrics

In [2]:
general_metrics = pl.read_csv(
    '/home/victor-hugo/HAVANA-2.0/data/processed/metrics/final_general_metrics.csv'
)

## Texas

In [3]:
(
    general_metrics
    .filter(
        (pl.col('state') == "Texas")
        & (
            (pl.col('embedder') == "hex2vec")
            | (pl.col('embedder') == "baseline")
        )
    )
    .select('embeddings_dimension', 'h3_resolution', 'f1_score', 'precision', 'recall')    
)

shape: (5, 5)
┌──────────────────────┬───────────────┬──────────┬───────────┬──────────┐
│ embeddings_dimension ┆ h3_resolution ┆ f1_score ┆ precision ┆ recall   │
│ ---                  ┆ ---           ┆ ---      ┆ ---       ┆ ---      │
│ i64                  ┆ i64           ┆ f64      ┆ f64       ┆ f64      │
╞══════════════════════╪═══════════════╪══════════╪═══════════╪══════════╡
│ 0                    ┆ 0             ┆ 0.414777 ┆ 0.471601  ┆ 0.401462 │
│ 32                   ┆ 7             ┆ 0.418479 ┆ 0.46981   ┆ 0.407188 │
│ 64                   ┆ 7             ┆ 0.415746 ┆ 0.475983  ┆ 0.401966 │
│ 64                   ┆ 8             ┆ 0.414124 ┆ 0.473671  ┆ 0.401384 │
│ 32                   ┆ 8             ┆ 0.415243 ┆ 0.470053  ┆ 0.403086 │
└──────────────────────┴───────────────┴──────────┴───────────┴──────────┘

In [4]:
(
    general_metrics
    .filter(
        (pl.col('state') == "Texas")
        & (
            (pl.col('embedder') == "poi-encoder")
            | (pl.col('embedder') == "baseline")
        )
    )
    .select('embeddings_dimension', 'h3_resolution', 'f1_score', 'precision', 'recall')    
)

shape: (5, 5)
┌──────────────────────┬───────────────┬──────────┬───────────┬──────────┐
│ embeddings_dimension ┆ h3_resolution ┆ f1_score ┆ precision ┆ recall   │
│ ---                  ┆ ---           ┆ ---      ┆ ---       ┆ ---      │
│ i64                  ┆ i64           ┆ f64      ┆ f64       ┆ f64      │
╞══════════════════════╪═══════════════╪══════════╪═══════════╪══════════╡
│ 0                    ┆ 0             ┆ 0.414777 ┆ 0.471601  ┆ 0.401462 │
│ 64                   ┆ 7             ┆ 0.432708 ┆ 0.480121  ┆ 0.423315 │
│ 32                   ┆ 7             ┆ 0.430051 ┆ 0.485696  ┆ 0.419468 │
│ 64                   ┆ 8             ┆ 0.425484 ┆ 0.477326  ┆ 0.412163 │
│ 32                   ┆ 8             ┆ 0.425687 ┆ 0.484529  ┆ 0.412054 │
└──────────────────────┴───────────────┴──────────┴───────────┴──────────┘

## California

In [5]:
(
    general_metrics
    .filter(
        (pl.col('state') == "California")
        & (
            (pl.col('embedder') == "hex2vec")
            | (pl.col('embedder') == "baseline")
        )
    )
    .select('embeddings_dimension', 'h3_resolution', 'f1_score', 'precision', 'recall')    
)

shape: (5, 5)
┌──────────────────────┬───────────────┬──────────┬───────────┬──────────┐
│ embeddings_dimension ┆ h3_resolution ┆ f1_score ┆ precision ┆ recall   │
│ ---                  ┆ ---           ┆ ---      ┆ ---       ┆ ---      │
│ i64                  ┆ i64           ┆ f64      ┆ f64       ┆ f64      │
╞══════════════════════╪═══════════════╪══════════╪═══════════╪══════════╡
│ 0                    ┆ 0             ┆ 0.38132  ┆ 0.461487  ┆ 0.362531 │
│ 32                   ┆ 7             ┆ 0.385865 ┆ 0.464184  ┆ 0.367726 │
│ 64                   ┆ 7             ┆ 0.384067 ┆ 0.457869  ┆ 0.366146 │
│ 64                   ┆ 8             ┆ 0.385669 ┆ 0.462959  ┆ 0.367724 │
│ 32                   ┆ 8             ┆ 0.386131 ┆ 0.4582    ┆ 0.369204 │
└──────────────────────┴───────────────┴──────────┴───────────┴──────────┘

In [6]:
(
    general_metrics
    .filter(
        (pl.col('state') == "California")
        & (
            (pl.col('embedder') == "poi-encoder")
            | (pl.col('embedder') == "baseline")
        )
    )
    .select('embeddings_dimension', 'h3_resolution', 'f1_score', 'precision', 'recall')    
)

shape: (5, 5)
┌──────────────────────┬───────────────┬──────────┬───────────┬──────────┐
│ embeddings_dimension ┆ h3_resolution ┆ f1_score ┆ precision ┆ recall   │
│ ---                  ┆ ---           ┆ ---      ┆ ---       ┆ ---      │
│ i64                  ┆ i64           ┆ f64      ┆ f64       ┆ f64      │
╞══════════════════════╪═══════════════╪══════════╪═══════════╪══════════╡
│ 0                    ┆ 0             ┆ 0.38132  ┆ 0.461487  ┆ 0.362531 │
│ 64                   ┆ 8             ┆ 0.388865 ┆ 0.434754  ┆ 0.379184 │
│ 32                   ┆ 8             ┆ 0.388323 ┆ 0.430812  ┆ 0.379163 │
│ 64                   ┆ 7             ┆ 0.378934 ┆ 0.450499  ┆ 0.365317 │
│ 32                   ┆ 7             ┆ 0.377309 ┆ 0.453901  ┆ 0.362885 │
└──────────────────────┴───────────────┴──────────┴───────────┴──────────┘

## Florida

In [7]:
(
    general_metrics
    .filter(
        (pl.col('state') == "Florida")
        & (
            (pl.col('embedder') == "hex2vec")
            | (pl.col('embedder') == "baseline")
        )
    )
    .select('embeddings_dimension', 'h3_resolution', 'f1_score', 'precision', 'recall')    
)

shape: (5, 5)
┌──────────────────────┬───────────────┬──────────┬───────────┬──────────┐
│ embeddings_dimension ┆ h3_resolution ┆ f1_score ┆ precision ┆ recall   │
│ ---                  ┆ ---           ┆ ---      ┆ ---       ┆ ---      │
│ i64                  ┆ i64           ┆ f64      ┆ f64       ┆ f64      │
╞══════════════════════╪═══════════════╪══════════╪═══════════╪══════════╡
│ 0                    ┆ 0             ┆ 0.447338 ┆ 0.490024  ┆ 0.439762 │
│ 32                   ┆ 8             ┆ 0.449772 ┆ 0.49357   ┆ 0.439599 │
│ 64                   ┆ 7             ┆ 0.451069 ┆ 0.502152  ┆ 0.439399 │
│ 32                   ┆ 7             ┆ null     ┆ null      ┆ null     │
│ 64                   ┆ 8             ┆ 0.449403 ┆ 0.500378  ┆ 0.436648 │
└──────────────────────┴───────────────┴──────────┴───────────┴──────────┘

In [8]:
(
    general_metrics
    .filter(
        (pl.col('state') == "Florida")
        & (
            (pl.col('embedder') == "poi-encoder")
            | (pl.col('embedder') == "baseline")
        )
    )
    .select('embeddings_dimension', 'h3_resolution', 'f1_score', 'precision', 'recall')    
)

shape: (5, 5)
┌──────────────────────┬───────────────┬──────────┬───────────┬──────────┐
│ embeddings_dimension ┆ h3_resolution ┆ f1_score ┆ precision ┆ recall   │
│ ---                  ┆ ---           ┆ ---      ┆ ---       ┆ ---      │
│ i64                  ┆ i64           ┆ f64      ┆ f64       ┆ f64      │
╞══════════════════════╪═══════════════╪══════════╪═══════════╪══════════╡
│ 0                    ┆ 0             ┆ 0.447338 ┆ 0.490024  ┆ 0.439762 │
│ 32                   ┆ 8             ┆ 0.472006 ┆ 0.519897  ┆ 0.459667 │
│ 64                   ┆ 8             ┆ 0.472083 ┆ 0.51568   ┆ 0.460541 │
│ 32                   ┆ 7             ┆ 0.454698 ┆ 0.510974  ┆ 0.445096 │
│ 64                   ┆ 7             ┆ 0.457937 ┆ 0.518671  ┆ 0.44638  │
└──────────────────────┴───────────────┴──────────┴───────────┴──────────┘

# All Metrics

In [80]:
def get_metrics(config: dict):
    metrics_path = "/home/victor-hugo/HAVANA-2.0/data/processed/metrics/"

    # Baseline metrics
    recall_baseline = pd.read_csv(
        f"/home/victor-hugo/HAVANA-2.0/data/processed/metrics/baseline/{config['state']}/recall_baseline.csv"
    )

    precision_baseline = pd.read_csv(
        f"/home/victor-hugo/HAVANA-2.0/data/processed/metrics/baseline/{config['state']}/precision_baseline.csv"
    )

    fscore_baseline = pd.read_csv(
        f"/home/victor-hugo/HAVANA-2.0/data/processed/metrics/baseline/{config['state']}/fscore_baseline.csv"
    )

    # region embeddings metrics
    recall_metrics = pd.read_csv(
        metrics_path + 
        f"{config['embedder']}/{config['state']}/recall_"
        + f"{config['embeddings_dimension']}_dimension_{config['h3_resolution']}_resolution.csv"
    )

    precision_metrics = pd.read_csv(
        metrics_path + 
        f"{config['embedder']}/{config['state']}/precision_"
        + f"{config['embeddings_dimension']}_dimension_{config['h3_resolution']}_resolution.csv"
    )

    fscore_metrics = pd.read_csv(
        metrics_path + 
        f"{config['embedder']}/{config['state']}/fscore_"
        + f"{config['embeddings_dimension']}_dimension_{config['h3_resolution']}_resolution.csv"
    )

    print("Diferença")
    print(f"Recall: {(recall_metrics.mean() - recall_baseline.mean()).sum()}")
    print(f"Precision: {(precision_metrics.mean() - precision_baseline.mean()).sum()}")
    print(f"F1-Score: {(fscore_metrics.mean() - fscore_baseline.mean()).sum()}")
    
    print("Proporção")
    print(f"Recall: {(recall_metrics.mean() / recall_baseline.mean()).mean()}")
    print(f"Precision: {(precision_metrics.mean() / precision_baseline.mean()).mean()}")
    print(f"F1-Score: {(fscore_metrics.mean() / fscore_baseline.mean()).mean()}")

In [113]:
config={
    "state": "Texas",
    "embedder": "poi-encoder",
    "embeddings_dimension": 32,
    "h3_resolution": 8
}
# Baseline metrics
recall_baseline = pd.read_csv(
    f"/home/victor-hugo/HAVANA-2.0/data/processed/metrics/baseline/{config['state']}/recall_baseline.csv"
)

precision_baseline = pd.read_csv(
    f"/home/victor-hugo/HAVANA-2.0/data/processed/metrics/baseline/{config['state']}/precision_baseline.csv"
)

fscore_baseline = pd.read_csv(
    f"/home/victor-hugo/HAVANA-2.0/data/processed/metrics/baseline/{config['state']}/fscore_baseline.csv"
)
metrics_path = "/home/victor-hugo/HAVANA-2.0/data/processed/metrics/"
# region embeddings metrics
recall_metrics = pd.read_csv(
    metrics_path + 
    f"{config['embedder']}/{config['state']}/recall_"
    + f"{config['embeddings_dimension']}_dimension_{config['h3_resolution']}_resolution.csv"
)

precision_metrics = pd.read_csv(
    metrics_path + 
    f"{config['embedder']}/{config['state']}/precision_"
    + f"{config['embeddings_dimension']}_dimension_{config['h3_resolution']}_resolution.csv"
)

fscore_metrics = pd.read_csv(
    metrics_path + 
    f"{config['embedder']}/{config['state']}/fscore_"
    + f"{config['embeddings_dimension']}_dimension_{config['h3_resolution']}_resolution.csv"
)

print(f"Recall: {(recall_metrics.mean() - recall_baseline.mean()).sum()}")
print(f"Precision: {(precision_metrics.mean() - precision_baseline.mean()).sum()}")
print(f"F1-Score: {(fscore_metrics.mean() - fscore_baseline.mean()).sum()}")

Recall: -0.3634701767473794
Precision: -0.6199172337266097
F1-Score: -0.6656610292512797

In [107]:
(fscore_metrics.mean() - fscore_baseline.mean())

Shopping        -0.003187
Community       -0.044343
Food            -0.077508
Entertainment   -0.090967
Travel          -0.108037
Outdoors        -0.082453
Nightlife       -0.112968
macro avg       -0.074209
weighted avg    -0.071989
dtype: float64

In [114]:
fscore_metrics.mean()

Shopping         0.341726
Community        0.214102
Food             0.308714
Entertainment    0.336106
Travel           0.390170
Outdoors         0.322856
Nightlife        0.470298
macro avg        0.340568
weighted avg     0.342644
dtype: float64

In [115]:
fscore_baseline.mean()

Shopping         0.344913
Community        0.258444
Food             0.386223
Entertainment    0.427072
Travel           0.498207
Outdoors         0.405310
Nightlife        0.583267
macro avg        0.414777
weighted avg     0.414632
dtype: float64

In [77]:
precision_metrics.mean()

Shopping         0.250638
Community        0.340460
Food             0.266985
Entertainment    0.377774
Travel           0.502508
Outdoors         0.388040
Nightlife        0.554884
dtype: float64

In [78]:
precision_baseline.mean()

Shopping         0.266615
Community        0.432680
Food             0.332448
Entertainment    0.454646
Travel           0.675440
Outdoors         0.476901
Nightlife        0.662476
dtype: float64

In [79]:
(precision_metrics.mean() - precision_baseline.mean())

Shopping        -0.015977
Community       -0.092220
Food            -0.065463
Entertainment   -0.076872
Travel          -0.172932
Outdoors        -0.088862
Nightlife       -0.107592
dtype: float64

In [45]:
(recall_metrics.mean() - recall_baseline.mean()).sum()

0.12603945704327355

## Texas

### poi-encoder

In [82]:
get_metrics(config={
    "state": "Texas",
    "embedder": "poi-encoder",
    "embeddings_dimension": 32,
    "h3_resolution": 7
})

Diferença
Recall: 0.12603945704327355
Precision: 0.09867045549665587
F1-Score: 0.13773574024181495
Proporção
Recall: 1.0475520499866504
Precision: 1.035695374552263
F1-Score: 1.0385903601145268

In [83]:
get_metrics(config={
    "state": "Texas",
    "embedder": "poi-encoder",
    "embeddings_dimension": 64,
    "h3_resolution": 7
})

Diferença
Recall: 0.15297401142910794
Precision: 0.059640246718668355
F1-Score: 0.16144646294171272
Proporção
Recall: 1.0600046914036774
Precision: 1.027592991229188
F1-Score: 1.0446009630869086

In [84]:
get_metrics(config={
    "state": "Texas",
    "embedder": "poi-encoder",
    "embeddings_dimension": 32,
    "h3_resolution": 8
})

Diferença
Recall: -0.3634701767473794
Precision: -0.6199172337266097
F1-Score: -0.6656610292512797
Proporção
Recall: 0.8608550486865856
Precision: 0.8223109191025089
F1-Score: 0.8265556577749456

In [85]:
get_metrics(config={
    "state": "Texas",
    "embedder": "poi-encoder",
    "embeddings_dimension": 64,
    "h3_resolution": 8
})

Diferença
Recall: 0.003757073741795791
Precision: 0.003610344173939184
F1-Score: 0.010354513454521264
Proporção
Recall: 1.005081924470092
Precision: 1.0044771813813225
F1-Score: 1.0050272461135934

### hex2vec

In [86]:
get_metrics(config={
    "state": "Texas",
    "embedder": "hex2vec",
    "embeddings_dimension": 32,
    "h3_resolution": 7
})

Diferença
Recall: 0.04008107961821089
Precision: -0.012535407793296205
F1-Score: 0.03361770515326207
Proporção
Recall: 1.0120062670850236
Precision: 1.0005173766722015
F1-Score: 1.0075529027525372

In [87]:
get_metrics(config={
    "state": "Texas",
    "embedder": "hex2vec",
    "embeddings_dimension": 64,
    "h3_resolution": 7
})

Diferença
Recall: 0.003527002154285863
Precision: 0.0306736785382416
F1-Score: 0.008905547165765582
Proporção
Recall: 1.0026798534842138
Precision: 1.0084521833879496
F1-Score: 1.0033453329398485

In [88]:
get_metrics(config={
    "state": "Texas",
    "embedder": "hex2vec",
    "embeddings_dimension": 32,
    "h3_resolution": 8
})

Diferença
Recall: 0.011371193237014965
Precision: -0.010835032643626119
F1-Score: 0.004394061004633465
Proporção
Recall: 1.0020577861657989
Precision: 0.9989023517240653
F1-Score: 1.0005476304305265

In [89]:
get_metrics(config={
    "state": "Texas",
    "embedder": "hex2vec",
    "embeddings_dimension": 64,
    "h3_resolution": 8
})

Diferença
Recall: -0.000545217130659803
Precision: 0.014489663773688821
F1-Score: -0.005469071612248577
Proporção
Recall: 0.9976246028758229
Precision: 1.0032439461053866
F1-Score: 0.9982333304904922

## California

### poi-encoder

In [90]:
get_metrics(config={
    "state": "California",
    "embedder": "poi-encoder",
    "embeddings_dimension": 32,
    "h3_resolution": 7
})

Diferença
Recall: 0.0024779586975637036
Precision: -0.05310576159614647
F1-Score: -0.034064014015396105
Proporção
Recall: 0.9960902725845812
Precision: 1.0019983131536043
F1-Score: 0.9947260460460119

In [91]:
get_metrics(config={
    "state": "California",
    "embedder": "poi-encoder",
    "embeddings_dimension": 64,
    "h3_resolution": 7
})

Diferença
Recall: 0.019501587660702063
Precision: -0.0769157497254386
F1-Score: -0.019851181913046245
Proporção
Recall: 1.0080755043498573
Precision: 0.9954941587393487
F1-Score: 0.9995902225853937

In [92]:
get_metrics(config={
    "state": "California",
    "embedder": "poi-encoder",
    "embeddings_dimension": 32,
    "h3_resolution": 8
})

Diferença
Recall: -0.585624084007522
Precision: -1.406310073169432
F1-Score: -1.2419128248675602
Proporção
Recall: 0.7400673207002803
Precision: 0.6012587090673956
F1-Score: 0.6418600576813005

In [93]:
get_metrics(config={
    "state": "California",
    "embedder": "poi-encoder",
    "embeddings_dimension": 64,
    "h3_resolution": 8
})

Diferença
Recall: 0.07907247469164574
Precision: -0.22595461645932943
F1-Score: 0.01866834550715754
Proporção
Recall: 1.0330586290742114
Precision: 0.9597224449976359
F1-Score: 1.0039341330630278

### hex2vec

In [94]:
get_metrics(config={
    "state": "California",
    "embedder": "hex2vec",
    "embeddings_dimension": 32,
    "h3_resolution": 7
})

Diferença
Recall: 0.036365052489197414
Precision: 0.018874996903712943
F1-Score: 0.04062606474812103
Proporção
Recall: 1.0180889252543486
Precision: 1.0067797398332359
F1-Score: 1.0127682370277593

In [95]:
get_metrics(config={
    "state": "California",
    "embedder": "hex2vec",
    "embeddings_dimension": 64,
    "h3_resolution": 7
})

Diferença
Recall: 0.02530544378317154
Precision: -0.0253270677337806
F1-Score: 0.02445027980859993
Proporção
Recall: 1.0127497522745161
Precision: 0.9969703783005412
F1-Score: 1.0071406834678847

In [96]:
get_metrics(config={
    "state": "California",
    "embedder": "hex2vec",
    "embeddings_dimension": 32,
    "h3_resolution": 8
})

Diferença
Recall: 0.046707672776412607
Precision: -0.02301397067997943
F1-Score: 0.043061588789591876
Proporção
Recall: 1.0201465874633517
Precision: 0.9989595090287964
F1-Score: 1.011623662002953

In [97]:
get_metrics(config={
    "state": "California",
    "embedder": "hex2vec",
    "embeddings_dimension": 64,
    "h3_resolution": 8
})

Diferença
Recall: 0.03634754738523177
Precision: 0.010300981666280573
F1-Score: 0.03876577440472084
Proporção
Recall: 1.0180496502042118
Precision: 1.006426461970926
F1-Score: 1.0124229103408247

## Florida

### poi-encoder

In [98]:
get_metrics(config={
    "state": "Florida",
    "embedder": "poi-encoder",
    "embeddings_dimension": 32,
    "h3_resolution": 7
})

Diferença
Recall: 0.03734040630019833
Precision: 0.1466505015127385
F1-Score: 0.06672063111674378
Proporção
Recall: 1.0048764399739925
Precision: 1.0382723542668473
F1-Score: 1.0137000399644736

In [99]:
get_metrics(config={
    "state": "Florida",
    "embedder": "poi-encoder",
    "embeddings_dimension": 64,
    "h3_resolution": 7
})

Diferença
Recall: 0.04632374003841924
Precision: 0.20052583693280396
F1-Score: 0.09542666287544782
Proporção
Recall: 1.01139053799749
Precision: 1.0532119091711278
F1-Score: 1.0229835964440521

In [100]:
get_metrics(config={
    "state": "Florida",
    "embedder": "poi-encoder",
    "embeddings_dimension": 32,
    "h3_resolution": 8
})

Diferença
Recall: 0.05229871178699452
Precision: 0.09062984962337933
F1-Score: 0.10049936882374738
Proporção
Recall: 1.0363731192356749
Precision: 1.0242363796470015
F1-Score: 1.0309721851078686

In [101]:
get_metrics(config={
    "state": "Florida",
    "embedder": "poi-encoder",
    "embeddings_dimension": 64,
    "h3_resolution": 8
})

Diferença
Recall: 0.045735199725343206
Precision: 0.05613950732116407
F1-Score: 0.08498189001762607
Proporção
Recall: 1.034480366859517
Precision: 1.0185405385858108
F1-Score: 1.0273501289493536

### hex2vec

In [102]:
get_metrics(config={
    "state": "Florida",
    "embedder": "hex2vec",
    "embeddings_dimension": 32,
    "h3_resolution": 7
})

Diferença
Recall: 0.019081481355116503
Precision: 0.10158223524966609
F1-Score: 0.06770107762617561
Proporção
Recall: 1.0147510082679863
Precision: 1.0226913588565172
F1-Score: 1.017553767751946

In [103]:
get_metrics(config={
    "state": "Florida",
    "embedder": "hex2vec",
    "embeddings_dimension": 64,
    "h3_resolution": 7
})

Diferença
Recall: -0.0025382837273498493
Precision: 0.08489692682937561
F1-Score: 0.033912764693917186
Proporção
Recall: 1.0014812312914547
Precision: 1.0180536079677576
F1-Score: 1.007898840645515

In [104]:
get_metrics(config={
    "state": "Florida",
    "embedder": "hex2vec",
    "embeddings_dimension": 32,
    "h3_resolution": 8
})

Diferença
Recall: -0.0011385440123261592
Precision: 0.024820921986726585
F1-Score: 0.02178600942250003
Proporção
Recall: 1.0058831692767227
Precision: 1.0042953331578146
F1-Score: 1.0070007310721683

In [105]:
get_metrics(config={
    "state": "Florida",
    "embedder": "hex2vec",
    "embeddings_dimension": 64,
    "h3_resolution": 8
})

Diferença
Recall: -0.02179981573024148
Precision: 0.07247730805907537
F1-Score: 0.018901818788074065
Proporção
Recall: 1.0041741698715472
Precision: 1.0119257907494537
F1-Score: 1.0064038468899323